project:
  type: website
  output-dir: docs

website:
  title: "jasmine cabrera"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full



