project:
  type: website
  output-dir: docs

website:
  title: "jasmine cabrera"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: media/aprilresume.pdf
        text: CV
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full



